name: Generate RootFS

on:
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Generate rootfs
        run: ./generate-rootfs.sh

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: rootfs.ext4
